### PR TITLE
Bugfixes for 'rename-run-info' found during SW integration while tagg…

### PR DESCRIPTION
**Pull request by QATCH-Technologies**
…ing nanovis SW v2.6b50

### CODE REVIEW

**Comment by QATCH-Technologies** [comment]
Bugs found/fixed:
- `self.loaded_datapath` needed to be set to new path
- `key` not updated in `self.run_timestamps` dictionary
- superclass should not be removed from `RunInfoWindow`
- added 4th `str` to `updated_run` signal to address (1) above
- only call `self.update_run_name` on PARAMS call of Run Info
- only modify XML name/signature if Run Info name changed
- only `emit` to new rename signals if/when files were changed
- if an error occurs during rename, continue to write XML audit

**Comment by QATCH-Technologies** [comment]
TODO: The selected run in the dropdown list of Analyze goes back to the first entry still. The selected index should be set to the loaded run after `updateRuns()` rebuilds the entire list.

**Comment by QATCH-Technologies** [comment]
TODO: If the user changes the cAsE of the run's name, it throws an error and does not change the XML root name accordingly.

To reproduce: change the case of a run, without changing the actual text (i.e. "open_unbundled_ethernet_1" -> "open_unbundled_Ethernet_1" and click to Save the Run Info. 

Solution: Even when the target "already exists", if (and only if) the existing location is this the same as this run, and `old_name != new_name` then you still have to perform the rename operation both on the filesystem and in the XML audit records.

The log messages observed:
17:33:48,412 INFO [RunInfo] Path logged_data\1_12438990\open_unbundled_Ethernet_1 already exists, no action taken.
17:33:48,417 ERROR [RunInfo] Could not update directory due path error.

**Comment by QATCH-Technologies** [comment]
TODO: `runInfo.py:19` change breaks saving multiplex runs. Why was this signal modified?

**Comment by PaulMacNichol** [comment]
> TODO: `runInfo.py:19` change breaks saving multiplex runs. Why was this signal modified?

TODO is fixed.  Not merged to main.

**Comment by PaulMacNichol** [comment]
> TODO: The selected run in the dropdown list of Analyze goes back to the first entry still. The selected index should be set to the loaded run after `updateRuns()` rebuilds the entire list.

Fixed with latest commit to branch.

**Pull request merged**
