### PR TITLE
Run info rename

### PR DESCRIPTION
**Pull request by PaulMacNichol**
Should be working now

### CODE REVIEW

**Comment by QATCH-Technologies** [comment]
@PaulMacNichol I just added a commit with some comments in-line regarding some outstanding TODOs and a new NOTE for your review.

**Review by QATCH-Technologies — CHANGES_REQUESTED** [review]
Looks good, I added a few comments for you to review and we can finalize this all on Friday
I need to test with an actual device running PYCODE in the lab to see how it works with hard symbolic links in the directory tree. My commit DIFF: https://github.com/QATCH-Technologies/nanovisQ/pull/15/commits/f24b999c8e6eecd896cee6130c88f1646a2ec14d

**Comment by QATCH-Technologies** [comment]
image

### Verification Issue
Run name in "Run" list and the "Loaded" run name are stale after a run is renamed

### Steps to reproduce
1. Load a run from the "Run" list
2. The "Loaded" run shows the [current run name]
3.  Open "Run Info" and modify the Run Name to the [new run name]
4. Save the Run Info dialog, entering initials if prompted
5. Observe the "Run" list and "Loaded" run names are still showing [current run name]

### Expectation
At step 5, the "Run" list and "Loaded" run names should be showing [new run name].

### Suggested Solution
After a run is renamed, but only after a _new_ run name is entered (not after every save of Run Info), the cached list of runs and the "Loaded" run text should be updated to reflect the new name of the currently selected run. Modifying the cached values is much faster than forcing a complete "Rescan" and "Load" of the run when we know exactly what was changed about the run.

**Comment by QATCH-Technologies** [comment]
image
The resulting XML of a run after the run name was changed using Run Info

### Verification Issue
The `run_info.signature` is no longer valid after changing the `run_info.name` parameter. 

### Steps to reproduce
1. Store a copy of the initial XML audit file for later comparison for any given run
2. Rename the run using Run Info, and save, entering initials if prompted
3. Compare the newly created XML audit file to the initial XML audit file
4. Correctly, there are new <audit> and <params> records in the XML and `run_info.name` was updated
5. However, `run_info.name` was changed without changing the associated `signature` field, invalidating it

### Expectation
To maintain audit records that will pass an audit check per CFR Part 11 compliance, the encapsulated `signature` field of the <run_info> record must also be updated when changing the one or more of the other fields in the <run_info> record after receiving the proper user authorization to perform such an operation. Failure to update the `signature` field makes the `name` change appear to have been made without proper authorization and/or without following the allowed mechanisms to do so in SW (i.e. an audit would reveal that the user must have changed the field in the XML manually when they in fact did not). 

### Suggested Solution
Since this is a deliberate and user-authorized change with an associated <audit> logged in the XML to justify its new value, when changing the `run_info.name` parameter in this code flow, the `run_info.signature` parameter should also be re-calculated and updated to reflect the new correct hash value as well.

**Comment by QATCH-Technologies** [comment]
### Verification Success
PYCODE builds with symbolic links for the "logged_data" directory can rename runs without encountering the blocking condition in code, so long as the "capture.zip" and XML are nested at least 2 directories deep into the "logged_data" parent directory (i.e. "logged_data\device\run\run.xml")

### Important Exception
I suspect that a folder structure of "logged_data\dummy\run.xml" likely would not work with this rename code as in this scenario the `grandparent_dir` is a linked directory, and it would fail the condition at `runInfo.py:1871`. This is something to keep in mind once we allow the user to "configure data" with custom save paths for folder and file naming in the near future.

**Comment by PaulMacNichol** [comment]
> ### Verification Issue
> Upon saving Run Info after renaming, the "Run" list dropdown menu reverts to showing the "most recent" run as selected
> 
> ### Steps to reproduce
> 1. Load a run from the "Run" list, other than the most recent (top of list)
> 2. The "Run" combobox and "Loaded" text show the loaded run's name
> 3. Open "Run Info" and modify the Run Name to a different run name
> 4. Save the Run Info dialog, entering initials if prompted
> 5. Observe the "Run" list combobox's text has changed to the first entry
> 
> ### Expectation
> When renaming a run, the "Run" list and "Loaded" run names should consistently show the current run's name
> 
> ### Suggested Solution
> After a run is renamed, but only after a _new_ run name is entered (not after every save of Run Info), the cached list of runs and the "Loaded" run text should be updated to reflect the new name of the currently selected run. It looks like something is being reloaded to cause the selected index of the "Run" list to revert to the first entry, but it should remain selected on the currently loaded run in the list (at the same `index` but under it's _new_ run name).

I believe the previous patch also fixes this.

**Comment by PaulMacNichol** [comment]
> image The resulting XML of a run after the run name was changed using Run Info
> 
> ### Verification Issue
> The `run_info.signature` is no longer valid after changing the `run_info.name` parameter.
> 
> ### Steps to reproduce
> 1. Store a copy of the initial XML audit file for later comparison for any given run
> 2. Rename the run using Run Info, and save, entering initials if prompted
> 3. Compare the newly created XML audit file to the initial XML audit file
> 4. Correctly, there are new "audit" and "params" records in the XML and `run_info.name` was updated
> 5. However, `run_info.name` was changed without changing the associated `signature` field, invalidating it
> 
> ### Expectation
> To maintain audit records that will pass an audit check per CFR Part 11 compliance, the encapsulated `signature` field of the "run_info" record must also be updated when changing the one or more of the other fields in the "run_info" record after receiving the proper user authorization to perform such an operation. Failure to update the `signature` field makes the `name` change appear to have been made without proper authorization and/or without following the allowed mechanisms to do so in SW (i.e. an audit would reveal that the user must have changed the field in the XML manually when they in fact did not).
> 
> ### Suggested Solution
> Since this is a deliberate and user-authorized change with an associated "audit" logged in the XML to justify its new value, when changing the `run_info.name` parameter in this code flow, the `run_info.signature` parameter should also be re-calculated and updated to reflect the new correct hash value as well.

Hard to tell if its the correct signature from my end but the `run_info.signature` field is certainly changing now.  I believe this is fixed.

**Comment by PaulMacNichol** [comment]
Grandparent directory is not a concern.  Remove it from symbolic links.

**Pull request merged**
